name: iconsax_linear
description: "Iconsax Linear icon pack for flutter."
version: 1.1.0
homepage: https://iconsax.io/
repository: https://github.com/shaaanuu/Iconsax-Linear
topics:
  - icons
  - iconsax
  - flutter
  - dart
  - linear

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: IconsaxLinear
      fonts:
        - asset: lib/iconsax_linear.ttf
